### ISSUE TITLE
Tangent Technologies - Epic Mission #1

### ISSUE THREAD

**Issue by supaz** [NCC-Lykos/neocron-classic#160]
For the first TT mission the Diammond's broker in Diammond's HQ is named Malcolm Ambrosius instead of John Duvall.
So mission doesn't work.

**Comment by RorixBladewing** [comment]
The Broker is located in the DRE Store at Plaza 1

**Comment by tuxhomer** [comment]
for me, the brocker in the dre HQ worked

**Comment by ghost** [comment]
@supaz If you're using the Wiki as a reference guide for the Epic Run, the actual name of the Broker itself doesn't matter as they're dynamically generated.  The problem here is the mission system isn't picking up on proper target for the NPC to talk to.

Sending this over to @NCC-Therenall to work on :)

**Comment by supaz** [comment]
Ok i relaunched the mission and this time it worked with plaza 1 broker.

**Comment by ghost** [comment]
I'm closing this for now.  I've re-ran this part of the Tangent Technologies epic this morning, and the display pointer correctly displayed pointing to a DRE Vendor within Plaza SEC-1.
