### ISSUE TITLE
Zone Crash - RPOS Bug

### ISSUE THREAD

**Issue by Stevil79** [NCC-Lykos/neocron-classic#170]
RPOS resets after zone crash. Only happened once. Thought we eliminated this one!!

**Comment by M-ace** [comment]
there is a work around for this one.  in the clients folder >retail>ini>rpos.ini    right click the file >properties tick the read only box.  now when the client crashes it wont reset your rpos.  it will make it so that the rpos settings are set the same forever.  if u ever wish to change stuff around again to a more perm spot u will have to uncheck that box, then make changes and log out.  dont alt f4 when saving settings either.

**Comment by M-ace** [comment]
this work around has been the same on nc2 also for at least a decade.

**Comment by NCC-Vali** [comment]
Can confirm this is still an issue, just happened to me.

**Comment by NCC-Lykos** [comment]
This should be fixed now.
