### ISSUE TITLE
BioTech Epic

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#216]
Creating this issue for tracking purposes.

:heavy_check_mark:  Mission 1: NPC Pointers and Mission Dialog Window works.

:stop_sign: Mission 2: NO NPC Pointers or Mission Dialog Window text.
* You can still follow the mission instructions and complete the mission.

:stop_sign: Mission 3: NO NPC Pointers or Mission Dialog Window text.
* With Mission 3 - When you kill the mutant spawns outside, they don't show in the chat-log as counting towards the kills required, nor do does the mission objective completed come up.  However, once you kill the 5th mutant, Beckert talks to you and the mission can be completed.
* You can still follow the mission instructions and complete the mission.

:heavy_check_mark:  Mission 4: NPC Pointers and Mission Dialog Window works.

:heavy_check_mark:  Mission 5: NPC Pointers and Mission Dialog Window works.

:heavy_check_mark:  Mission 6: NPC Pointers and Mission Dialog Window works.

**Comment by ghost** [comment]
Relogging while on Missions 2 and 3 cause the dialogs to behave normally.

**Comment by M-ace** [comment]
my mission 1 was bugged.  i didnt get mission successfuls when i completed the task, nor did i get my money or xp when i finished.  when i started mission 2 it said mission 1 failed, mission 2 accepted and i noticed i had no pointers.  i then crashed.  when i came back ingame i had pointers and everything seemed fine.  then when i got to mission 4 i wasnt getting the counter for killing the mutants corps.  so i relogged because i got aggro from doy unit.  after relog the counter was showing how many i had remaining.  so in all these cases, relogging fixed the issues, but u shouldnt have to relog after starting a mission for it to act right

**Comment by ghost** [comment]
Closing this issue out as a lot of these issues have been resolved and these issues not updated at the same time.
