### ISSUE TITLE
Zero health won't die 

### ISSUE THREAD

**Issue by brawl-uk** [NCC-Lykos/neocron-classic#248]
Notices sometimes mob health reaches 0 and still live after a clear shot on nil health a war bot took 4 clear shots today with commando sniper rifle and wouldn't die had to relog and still took 2 shots to down him.

**Comment by ghost** [comment]
This is a known problem with Neocron for _years_, we will be able to address this issue during our netcode deployment.

**Comment by Corruptforce** [comment]
Not the same issue, but quite often hits don't register if they're slightly obscured by terrain/objects - yet show damage client side.

I'm assuming this is the client thinking there is a clear line of fire, but the server saying there isn't.
Either way both issues should be fixed with the netcode update as @NCC-Gnisha says.

**Comment by ghost** [comment]
Closing this for now.  Can revisit this with netcode to verify.
