### ISSUE TITLE
Using drones messes up HUD

### ISSUE THREAD

**Issue by rhomm-dev** [NCC-Lykos/neocron-classic#330]
## Issue

Using a drone messes up the HUD by jumbling the chat and nearby players windows, it also appears to persist these settings somewhat in the *rpos.ini* settings file.

## Reproduce by

Activating and deactivating a drone

## Screenshot

![ncc_drone_breaks_hud](https://user-images.githubusercontent.com/34965105/47975422-b9f15400-e07b-11e8-8033-e763f30ed0c1.png)

**Comment by ghost** [comment]
This one is most likely a side effect from the RPOS scaling changes that we've recently implemented.  Will have Zodiac take a look at this one.

**Comment by NCC-Therenall** [comment]
Just to keep this updated: This isn't something we are probably going to put a very high priority on right now, drones aren't officially supported as they have other issues anyways. 

I'll leave this issue open because it needs to be fixed, but there's other things that will probably take priority for now.

**Comment by NCC-Lykos** [comment]
Drones are disabled at this time, will be fixed when drones are reworked.
