### ISSUE TITLE
NEXT epic regression

### ISSUE THREAD

**Issue by rhomm-dev** [NCC-Lykos/neocron-classic#333]
# Issue

The NPC (Biotech Director @ Chez Sypher in Via Rosso SEC-1) for the first NEXT epic mission does not accept the mission item. It may be that the wrong NPC is spawning here or more general mission-related issues.

# Reproduce by

Attempt the very first mission of the NEXT epic

# Screenshot

![ncc_next_epic_regression](https://user-images.githubusercontent.com/34965105/48947024-baa03c00-eefd-11e8-97c5-d4f7e323571f.png)

**Comment by ghost** [comment]
The issue here is that the first mission of the NEXT epic isn't starting.  Similar to what's happening with the Tangent Technologies Mission #6.  Bringing this issue to the attention of @NCC-Therenall so look into as this is probably related to the existing mission system issues that we're experiencing.

**Comment by ghost** [comment]
So just an update on this for those following it. I've finally been able to replicate this issue locally, but its a tricky one. But we're working on it!

**Comment by NCC-Lykos** [comment]
Fixed.
